export type TrackType = 'general' | 'social' | 'professional' | 'dating';

export interface Level {
    id: string;
    title: string;
    description: string;
    xp: number;
    track: TrackType;
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    opener: string;
    aiCharacter: {
        role: string;
        voiceId?: string;
    };
    systemPrompt: string;
    context: {
        situation: string;
        action: string;
        goal: string;
    };
    order: number;
}

export const LEVELS: Level[] = [
    // --- ASSESSMENTS ---
    {
        id: "assessment-social",
        title: "Social Baseline",
        description: "Establish your starting social score.",
        xp: 0,
        track: "social",
        difficulty: "Beginner",
        opener: "Hey! I haven't seen you since college. How have you been?",
        aiCharacter: { role: "Old Friend" },
        systemPrompt: "You are an old college friend running into the user at a coffee shop. You are warm, surprised, and curious. Ask open-ended questions to catch up. Keep responses concise (under 2 sentences). Purpose: Assess user's warmth and conversational flow.",
        context: {
            situation: "You just bumped into an old college friend at a coffee shop.",
            action: "Catch up naturally and show warmth.",
            goal: "Keep the conversation flowing for 60 seconds."
        },
        order: 0
    },
    {
        id: "assessment-dating",
        title: "Dating Baseline",
        description: "Find your baseline charm score.",
        xp: 0,
        track: "dating",
        difficulty: "Beginner",
        opener: "So, I noticed you have a picture of hiking on your profile. Do you do that often?",
        aiCharacter: { role: "Date" },
        systemPrompt: "You are on a first date. You are slightly nervous but interested. You just asked about a hiking photo. Engage with their response flirty but subtle. Keep responses concise. Purpose: Assess user's charm and playful banter.",
        context: {
            situation: "You are on a first date having drinks.",
            action: "Respond effortlessly to a question about your hobbies.",
            goal: "Build attraction and show charm."
        },
        order: 0
    },
    {
        id: "assessment-professional",
        title: "Professional Baseline",
        description: "See where you stand professionally.",
        xp: 0,
        track: "professional",
        difficulty: "Beginner",
        opener: "Thanks for coming in. Tell me a bit about a project you led recently.",
        aiCharacter: { role: "Interviewer" },
        systemPrompt: "You are a hiring manager. You are professional, direct, but polite. Ask follow-up questions about their leadership. Keep responses concise. Purpose: Assess user's clarity and authority.",
        context: {
            situation: "You are in a high-stakes job interview.",
            action: "Describe a recent leadership experience clearly.",
            goal: "Demonstrate competence and authority."
        },
        order: 0
    },
    {
        id: "0",
        title: "Baseline Assessment",
        description: "Your starting point.",
        xp: 0,
        track: "general",
        difficulty: "Beginner",
        opener: "Hi there! I'm ready to help you find your baseline charisma score. Briefly introduce yourself.",
        aiCharacter: { role: "Coach" },
        systemPrompt: "You are a charisma coach assessing the user's voice.",
        context: {
            situation: "You are checking in with your AI coach.",
            action: "Introduce yourself.",
            goal: "Do not worry, just speak naturally."
        },
        order: 0
    },

    // --- DATING TRACK ---
    {
        id: "dating-1",
        title: "Approaching a Stranger",
        description: "Learn to break the ice naturally.",
        xp: 100,
        track: "dating",
        difficulty: "Beginner",
        opener: "Excuse me, I couldn't help but notice the book you're reading. Is it any good?",
        aiCharacter: { role: "Stranger at Bookstore" },
        systemPrompt: "Be open but slightly cautious. Respond to the user's energy.",
        context: { situation: "In a bookstore.", action: "Start a conversation.", goal: "Be natural." },
        order: 1
    },
    {
        id: "dating-2",
        title: "Playful Teasing",
        description: "Master the art of banter.",
        xp: 200,
        track: "dating",
        difficulty: "Intermediate",
        opener: "You ordered pineapple on pizza? Really? I thought you had good taste.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Tease the user playfully. See if they can handle banter.",
        context: { situation: "First date dinner.", action: "Handle the teasing.", goal: "Keep it fun." },
        order: 2
    },
    {
        id: "dating-3",
        title: "Deep Connection",
        description: "Move beyond surface level talk.",
        xp: 300,
        track: "dating",
        difficulty: "Advanced",
        opener: "I feel like everyone just presents a highlight reel these days. What's something real you're dealing with?",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be vulnerable. See if the user can match the depth.",
        context: { situation: "Late night walk.", action: "Share something real.", goal: "Build intimacy." },
        order: 3
    },
    {
        id: "dating-4",
        title: "Handling a Rejection",
        description: "Stay high-value when told no.",
        xp: 150,
        track: "dating",
        difficulty: "Intermediate",
        opener: "I'm flattered, but I think I just see us more as friends.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Deliver a rejection politely. Observe if they get defensive.",
        context: { situation: "Ending a date.", action: "Accept rejection gracefully.", goal: "Maintain high value." },
        order: 4
    },
    {
        id: "dating-5",
        title: "Suggesting a Second Date",
        description: "Be confident, not needy.",
        xp: 100,
        track: "dating",
        difficulty: "Beginner",
        opener: "I had a really good time today. Did you?",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be curious about the future. Wait for the user to lead.",
        context: { situation: "Walking to their car.", action: "Propose a next meeting.", goal: "Secure the date." },
        order: 5
    },

    // ... (Adding representative samples for brevity, AI will generate the rest as requested)
    {
        id: "dating-k-3",
        title: "Flirting in a Crowd",
        description: "Create a private moment in public.",
        xp: 200,
        track: "dating",
        difficulty: "Intermediate",
        opener: "It's so loud in here, I can barely hear myself think. What were you saying?",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be distracted by the crowd. See if they can pull you back in.",
        context: { situation: "Crowded bar.", action: "Create a deep connection.", goal: "Ignore the noise." },
        order: 6
    },
    {
        id: "dating-k-4",
        title: "Complimenting with Intent",
        description: "Master non-generic compliments.",
        xp: 100,
        track: "dating",
        difficulty: "Beginner",
        opener: "You've been staring at me for a while. Is there something on my face?",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be playful. Challenge the user's stare.",
        context: { situation: "Sitting across from each other.", action: "Give a genuine compliment.", goal: "Be specific." },
        order: 7
    },
    {
        id: "dating-k-5",
        title: "The 'Friendzone' Exit",
        description: "Shift the dynamic to romantic.",
        xp: 300,
        track: "dating",
        difficulty: "Advanced",
        opener: "You're like the brother I never had. I can tell you anything!",
        aiCharacter: { role: "Close Friend" },
        systemPrompt: "Friendzone the user hard. See if they can break the frame.",
        context: { situation: "Hanging out at home.", action: "Shift the romantic dynamic.", goal: "Break the 'brother' frame." },
        order: 8
    },
    {
        id: "dating-k-6",
        title: "The First Awkward Silence",
        description: "Hold the tension or break it smoothly.",
        xp: 150,
        track: "dating",
        difficulty: "Intermediate",
        opener: "... So ... yeah.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Stop talking and let an awkward silence linger.",
        context: { situation: "Mid-conversation.", action: "Handle the silence.", goal: "Don't panic." },
        order: 9
    },
    {
        id: "dating-k-7",
        title: "Meeting the Parents",
        description: "Balance warmth and respect.",
        xp: 250,
        track: "dating",
        difficulty: "Advanced",
        opener: "So, what exactly are your intentions with my daughter?",
        aiCharacter: { role: "Strict Father" },
        systemPrompt: "Be intimidating and direct.",
        context: { situation: "Living room intro.", action: "Answer the tough question.", goal: "Gain respect." },
        order: 10
    },
    {
        id: "dating-k-8",
        title: "Discussing Shared Values",
        description: "Talk about the big things early.",
        xp: 200,
        track: "dating",
        difficulty: "Intermediate",
        opener: "Is family important to you? Or are you more of a career person?",
        aiCharacter: { role: "Date" },
        systemPrompt: "Ask a serious question about values.",
        context: { situation: "Dinner talk.", action: "Express your values clearly.", goal: "Show alignment." },
        order: 11
    },
    {
        id: "dating-k-9",
        title: "Handling a Distracted Date",
        description: "Get their attention back gracefully.",
        xp: 200,
        track: "dating",
        difficulty: "Intermediate",
        opener: "(Looking at phone) Oh sorry, what did you say? My friend just texted.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be rude and check your phone often.",
        context: { situation: "During dinner.", action: "Re-engage them without being needy.", goal: "Put the phone away." },
        order: 12
    },
    {
        id: "dating-k-10",
        title: "Explaining Your Passions",
        description: "Make 'geeky' topics sound sexy.",
        xp: 100,
        track: "dating",
        difficulty: "Beginner",
        opener: "I see you're really into medieval history. Isn't that a bit... dry?",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be slightly judgmental about their hobby.",
        context: { situation: "Casual chat.", action: "Explain your passion with energy.", goal: "Make them intrigued." },
        order: 13
    },
    {
        id: "dating-k-11",
        title: "The 'Goodnight' Decision",
        description: "Read the room for the first kiss.",
        xp: 250,
        track: "dating",
        difficulty: "Advanced",
        opener: "Well, this is my door. I really enjoyed tonight.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Give mixed signals about wanting a kiss.",
        context: { situation: "At her door.", action: "Decide whether to go for the kiss.", goal: "Read the vibe." },
        order: 14
    },
    {
        id: "dating-k-12",
        title: "Handling a Late Arrival",
        description: "Address the disrespect without anger.",
        xp: 150,
        track: "dating",
        difficulty: "Intermediate",
        opener: "Oh my god, I'm so sorry I'm 30 minutes late! The traffic was insane.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be apologetic but see if they are a 'pushover'.",
        context: { situation: "Meeting at a bar.", action: "Address the lateness firmly but kindly.", goal: "Set a boundary." },
        order: 15
    },
    {
        id: "dating-k-13",
        title: "Competitive Banter",
        description: "Challenge them to a playful bet.",
        xp: 100,
        track: "dating",
        difficulty: "Beginner",
        opener: "I bet I can beat you at pool. I'm actually a pro.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be cocky and competitive.",
        context: { situation: "At a pool table.", action: "Engage in the bet.", goal: "Raise the stakes." },
        order: 16
    },
    {
        id: "dating-k-14",
        title: "Storytelling on a Date",
        description: "Keep them on the edge of their seat.",
        xp: 200,
        track: "dating",
        difficulty: "Intermediate",
        opener: "You said you went to Thailand last year? Tell me something crazy that happened.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be an eager listener. React to their story.",
        context: { situation: "Coffee date.", action: "Tell a compelling story.", goal: "Keep their attention." },
        order: 17
    },
    {
        id: "dating-k-15",
        title: "Disagreeing Softly",
        description: "Stand your ground on tastes.",
        xp: 150,
        track: "dating",
        difficulty: "Intermediate",
        opener: "I think that movie was absolute trash. How could you like it?",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be opinionated and slightly aggressive.",
        context: { situation: "Walking out of cinema.", action: "Explain your view without arguing.", goal: "Agree to disagree." },
        order: 18
    },
    {
        id: "dating-k-16",
        title: "Vulnerability Match",
        description: "Match their energy when things get real.",
        xp: 300,
        track: "dating",
        difficulty: "Advanced",
        opener: "I've never told anyone this, but I'm actually terrified of failing my new business.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Share a deep fear.",
        context: { situation: "Late night drinks.", action: "Empathize and share back.", goal: "Deepen the bond." },
        order: 19
    },
    {
        id: "dating-k-17",
        title: "Ending on a High",
        description: "Leave them wanting more.",
        xp: 200,
        track: "dating",
        difficulty: "Intermediate",
        opener: "Wait, you're leaving already? It's only 10 PM!",
        aiCharacter: { role: "Date" },
        systemPrompt: "Try to convince the user to stay.",
        context: { situation: "Mid-date.", action: "Leave early to maintain intrigue.", goal: "End on a high note." },
        order: 20
    },

    // --- SOCIAL TRACK ---
    {
        id: "social-1",
        title: "Small Talk Proficiency",
        description: "Turn boring waits into connections.",
        xp: 100,
        track: "social",
        difficulty: "Beginner",
        opener: "Man, this line is taking forever, right?",
        aiCharacter: { role: "Stranger" },
        systemPrompt: "Be a bit grumpy. See if they can cheer you up.",
        context: { situation: "Grocery store.", action: "Master the small talk.", goal: "Be charming." },
        order: 1
    },
    {
        id: "social-2",
        title: "Party Storyteller",
        description: "Hook your audience with a story.",
        xp: 150,
        track: "social",
        difficulty: "Intermediate",
        opener: "So, what's a crazy highlight of your year so far?",
        aiCharacter: { role: "Friend" },
        systemPrompt: "Be an audience member. See if the story is boring.",
        context: { situation: "House party.", action: "Tell an engaging story.", goal: "Capture the room." },
        order: 2
    },
    {
        id: "social-3",
        title: "De-escalation",
        description: "Handle tense situations with ease.",
        xp: 250,
        track: "social",
        difficulty: "Advanced",
        opener: "Hey, I think you cut in front of me.",
        aiCharacter: { role: "Stranger" },
        systemPrompt: "Be confrontational and annoyed.",
        context: { situation: "Busy bar line.", action: "De-escalate the tension.", goal: "Avoid a fight." },
        order: 3
    },
    {
        id: "social-4",
        title: "Entering a Group",
        description: "Join in without being awkward.",
        xp: 200,
        track: "social",
        difficulty: "Intermediate",
        opener: "... and then she said she didn't even like the dress! (Group laughs)",
        aiCharacter: { role: "Group Leader" },
        systemPrompt: "Be part of a tight-knit group. See if the user can break in.",
        context: { situation: "Networking mixer.", action: "Join the conversation.", goal: "Be included naturally." },
        order: 4
    },
    {
        id: "social-5",
        title: "Polite Exit",
        description: "Leave a talk without being rude.",
        xp: 100,
        track: "social",
        difficulty: "Beginner",
        opener: "So anyway, my aunt has this cat that only eats organic salmon...",
        aiCharacter: { role: "Talkative Stranger" },
        systemPrompt: "Talk endlessly about boring topics.",
        context: { situation: "Office kitchen.", action: "Exit the conversation.", goal: "Escape gracefully." },
        order: 5
    },
    {
        id: "social-k-7",
        title: "Giving a Toast",
        description: "Speak for the room.",
        xp: 250,
        track: "social",
        difficulty: "Advanced",
        opener: "Can I have everyone's attention? We'd love for someone to say a few words.",
        aiCharacter: { role: "Host" },
        systemPrompt: "Expect a short, heartfelt speech.",
        context: { situation: "Best friend's wedding.", action: "Deliver a perfect toast.", goal: "Make them cry/laugh." },
        order: 6
    },
    {
        id: "social-k-8",
        title: "Name Memory Gap",
        description: "Handle the 'forgot name' moment.",
        xp: 150,
        track: "social",
        difficulty: "Intermediate",
        opener: "Oh hey! We met at that wedding last month, remember?",
        aiCharacter: { role: "Stranger" },
        systemPrompt: "Be friendly but don't state your name.",
        context: { situation: "On the street.", action: "Find out their name gracefully.", goal: "Save face." },
        order: 7
    },
    {
        id: "social-k-9",
        title: "The Drunk Pivot",
        description: "Handle someone who is oversharing.",
        xp: 150,
        track: "social",
        difficulty: "Intermediate",
        opener: "So then I told my ex that she was a monster... (slurring)",
        aiCharacter: { role: "Drunk Stranger" },
        systemPrompt: "Be emotional and slightly loud.",
        context: { situation: "Late night bar.", action: "Redirect them or exit safely.", goal: "Maintain boundaries." },
        order: 8
    },
    {
        id: "social-k-10",
        title: "Asking for a Favor",
        description: "Don't sound like a burden.",
        xp: 100,
        track: "social",
        difficulty: "Beginner",
        opener: "Hey, are you busy this weekend? I might need a hand.",
        aiCharacter: { role: "Friend" },
        systemPrompt: "Be slightly hesitant to help.",
        context: { situation: "Over coffee.", action: "Ask to help with moving house.", goal: "Get a 'yes'." },
        order: 9
    },
    {
        id: "social-k-11",
        title: "Saying No Softly",
        description: "Decline without guilt.",
        xp: 100,
        track: "social",
        difficulty: "Beginner",
        opener: "Can you host the board game night? My house is a mess.",
        aiCharacter: { role: "Friend" },
        systemPrompt: "Be needy and expecting a 'yes'.",
        context: { situation: "Phone call.", action: "Say no to hosting.", goal: "Keep the friend happy." },
        order: 10
    },
    {
        id: "social-k-12",
        title: "Handling the Roast",
        description: "Own the frame with humor.",
        xp: 200,
        track: "social",
        difficulty: "Intermediate",
        opener: "Wow, nice shirt. Did you get it from a circus?",
        aiCharacter: { role: "Mocking Peer" },
        systemPrompt: "Be a bit of a bully with humor.",
        context: { situation: "Group hangout.", action: "Handle the roast.", goal: "Gain more respect." },
        order: 11
    },
    {
        id: "social-k-13",
        title: "Comforting a Friend",
        description: "Listen without fixing.",
        xp: 150,
        track: "social",
        difficulty: "Intermediate",
        opener: "I just feel like I'm failing at everything lately.",
        aiCharacter: { role: "Sad Friend" },
        systemPrompt: "Be vulnerable and looking for support.",
        context: { situation: "Quiet park.", action: "Provide emotional support.", goal: "Make them feel heard." },
        order: 12
    },
    {
        id: "social-k-14",
        title: "Introducing New People",
        description: "Connect two strangers well.",
        xp: 100,
        track: "social",
        difficulty: "Beginner",
        opener: "Wait, do I know your friend here?",
        aiCharacter: { role: "Acquaintance" },
        systemPrompt: "Be curious to meet the other person.",
        context: { situation: "Small gathering.", action: "Make a high-value intro.", goal: "Bridge the gap." },
        order: 13
    },
    {
        id: "social-k-15",
        title: "Disagreeing in a Group",
        description: "Be the voice of reason.",
        xp: 300,
        track: "social",
        difficulty: "Advanced",
        opener: "Everyone agrees we should just quit the plan, right?",
        aiCharacter: { role: "Group Peer" },
        systemPrompt: "Push for a group decision you disagree with.",
        context: { situation: "Group project.", action: "Offer a counter-view firmly.", goal: "Change their minds." },
        order: 14
    },
    {
        id: "social-k-16",
        title: "Handling a Loud Disruptor",
        description: "Calm the room with authority.",
        xp: 250,
        track: "social",
        difficulty: "Advanced",
        opener: "(Shouting) BUT THE PROBLEM IS NO ONE LISTENS!",
        aiCharacter: { role: "Loud Guest" },
        systemPrompt: "Be disruptive at a dinner.",
        context: { situation: "Dinner party.", action: "Calm the person down.", goal: "Restore peace." },
        order: 15
    },
    {
        id: "social-k-17",
        title: "Asking for Feedback",
        description: "Own your growth areas.",
        xp: 150,
        track: "social",
        difficulty: "Intermediate",
        opener: "Honestly? I think you can be a bit overbearing sometimes.",
        aiCharacter: { role: "Close Friend" },
        systemPrompt: "Deliver a harsh but true critique.",
        context: { situation: "One-on-one talk.", action: "Accept the feedback properly.", goal: "Earn their respect." },
        order: 16
    },
    {
        id: "social-k-18",
        title: "Ending a Dull Talk",
        description: "Pivots are everything.",
        xp: 100,
        track: "social",
        difficulty: "Beginner",
        opener: "... and then in 2012, I decided to switch banks...",
        aiCharacter: { role: "Boring Narrator" },
        systemPrompt: "Tell a very long, technical story.",
        context: { situation: "Wedding reception.", action: "Exit or pivot the talk.", goal: "Save your evening." },
        order: 17
    },
    {
        id: "social-k-19",
        title: "Sharing a Secret",
        description: "Build deep trust fast.",
        xp: 250,
        track: "social",
        difficulty: "Advanced",
        opener: "I trust you. I'm thinking about leaving my job.",
        aiCharacter: { role: "Friend" },
        systemPrompt: "Be hesitant about sharing but then open up.",
        context: { situation: "Late night drive.", action: "Share something vulnerable back.", goal: "Bond deeply." },
        order: 18
    },
    {
        id: "social-k-20",
        title: "Group Decision Lead",
        description: "Find consensus smoothly.",
        xp: 200,
        track: "social",
        difficulty: "Intermediate",
        opener: "I want pizza. He wants burgers. You decide!",
        aiCharacter: { role: "Hungry Friend" },
        systemPrompt: "Be indecisive and wait for leadership.",
        context: { situation: "Street corner.", action: "Make a firm, fair choice.", goal: "Everyone follows you." },
        order: 19
    },
    {
        id: "social-k-21",
        title: "The Compliment Challenge",
        description: "Compliment a stranger's vibe.",
        xp: 100,
        track: "social",
        difficulty: "Beginner",
        opener: "Oh, hi! Thanks for saying that.",
        aiCharacter: { role: "Stranger" },
        systemPrompt: "Be surprised and pleased.",
        context: { situation: "In an elevator.", action: "Give a specific compliment.", goal: "Leave on a high." },
        order: 20
    },

    // --- PROFESSIONAL TRACK ---
    {
        id: "professional-1",
        title: "The Elevator Pitch",
        description: "Sell yourself in 30 seconds.",
        xp: 100,
        track: "professional",
        difficulty: "Beginner",
        opener: "So, what do you do?",
        aiCharacter: { role: "Executive" },
        systemPrompt: "Be rushed. Expect impact.",
        context: { situation: "Elevator.", action: "Pitch your value.", goal: "Get a follow-up." },
        order: 1
    },
    {
        id: "professional-2",
        title: "Salary Negotiation",
        description: "Get paid what you are worth.",
        xp: 200,
        track: "professional",
        difficulty: "Intermediate",
        opener: "We can offer you $85k. That's our ceiling.",
        aiCharacter: { role: "HR Manager" },
        systemPrompt: "Be firm on budget. See if they move you.",
        context: { situation: "Offer meeting.", action: "Negotiate for $100k.", goal: "Increase the offer." },
        order: 2
    },
    {
        id: "professional-3",
        title: "Firing Someone",
        description: "Handle the hardest talk.",
        xp: 300,
        track: "professional",
        difficulty: "Advanced",
        opener: "You wanted to see me? Did I do something wrong?",
        aiCharacter: { role: "Underperformer" },
        systemPrompt: "Be clueless and defensive.",
        context: { situation: "Private office.", action: "Deliver the layoff/firing news.", goal: "Be clear and firm." },
        order: 3
    },
    {
        id: "professional-4",
        title: "Handling a Rude Peer",
        description: "Professionalism as a weapon.",
        xp: 150,
        track: "professional",
        difficulty: "Intermediate",
        opener: "That idea was pretty basic. Did you even try?",
        aiCharacter: { role: "Arrogant Colleague" },
        systemPrompt: "Be dismissive in front of others.",
        context: { situation: "Boardroom.", action: "Neutralize the rudeness.", goal: "Keep your authority." },
        order: 4
    },
    {
        id: "professional-5",
        title: "Promotion Ask",
        description: "Secure the next step.",
        xp: 250,
        track: "professional",
        difficulty: "Advanced",
        opener: "I've seen your work. It's solid, but we're not sure about a title change yet.",
        aiCharacter: { role: "Boss" },
        systemPrompt: "Be non-committal about their promotion.",
        context: { situation: "Annual review.", action: "Make a data-backed ask.", goal: "Get a timeline." },
        order: 5
    },
    {
        id: "professional-k-7",
        title: "Correcting a VP",
        description: "High stakes error correction.",
        xp: 300,
        track: "professional",
        difficulty: "Advanced",
        opener: "... which is why our 5% growth is excellent. (Actual growth is -2%)",
        aiCharacter: { role: "Senior VP" },
        systemPrompt: "Be very confident but wrong about a key stat.",
        context: { situation: "Big meeting.", action: "Fix the fact without embarrassment.", goal: "Protect the company." },
        order: 6
    },
    {
        id: "professional-k-8",
        title: "Competitor Networking",
        description: "Build bridges, keep secrets.",
        xp: 250,
        track: "professional",
        difficulty: "Advanced",
        opener: "So, what's really happening with your new product launch?",
        aiCharacter: { role: "Rival Rep" },
        systemPrompt: "Be friendly but trying to get secrets.",
        context: { situation: "Lounge mixer.", action: "Deflect while being likable.", goal: "Maintain secrecy." },
        order: 7
    },
    {
        id: "professional-k-9",
        title: "The Interview Hook",
        description: "Stand out in 60 seconds.",
        xp: 100,
        track: "professional",
        difficulty: "Beginner",
        opener: "Tell me something about you that isn't on your resume.",
        aiCharacter: { role: "Interviewer" },
        systemPrompt: "Look for personal drive and narrative.",
        context: { situation: "Job interview.", action: "Share a compelling story.", goal: "Get a 'wow'." },
        order: 8
    },
    {
        id: "professional-k-10",
        title: "Hard Follow-up Question",
        description: "Maintain poise under pressure.",
        xp: 200,
        track: "professional",
        difficulty: "Intermediate",
        opener: "Wait, if you spent $50k, where did the other $10k go?",
        aiCharacter: { role: "CEO" },
        systemPrompt: "Be suspicious about numbers.",
        context: { situation: "Budget presentation.", action: "Explain the gap clearly.", goal: "Maintain trust." },
        order: 9
    },
    {
        id: "professional-k-11",
        title: "Pitching a Risky Idea",
        description: "Gain buy-in for the new.",
        xp: 300,
        track: "professional",
        difficulty: "Advanced",
        opener: "This sounds risky. Why should we do this over the safe option?",
        aiCharacter: { role: "Risk Manager" },
        systemPrompt: "Be extremely skeptical.",
        context: { situation: "Strategy meeting.", action: "Sell the innovation.", goal: "Get approval." },
        order: 10
    },
    {
        id: "professional-k-12",
        title: "Client Apology",
        description: "Own it and save the deal.",
        xp: 250,
        track: "professional",
        difficulty: "Advanced",
        opener: "You guys really messed up this time. I'm considering cancelling.",
        aiCharacter: { role: "Angry Client" },
        systemPrompt: "Be ready to walk away.",
        context: { situation: "Panic call.", action: "Own the error and fix it.", goal: "Save the account." },
        order: 11
    },
    {
        id: "professional-k-13",
        title: "Negotiating Deadlines",
        description: "Push back without being lazy.",
        xp: 150,
        track: "professional",
        difficulty: "Intermediate",
        opener: "I need this on my desk in two hours. Go.",
        aiCharacter: { role: "Pushy Manager" },
        systemPrompt: "Be demanding and unreasonable.",
        context: { situation: "Afternoon rush.", action: "Ask for more time professionally.", goal: "Get a realistic deadline." },
        order: 12
    },
    {
        id: "professional-k-14",
        title: "Giving Peer Feedback",
        description: "Level up your teammate.",
        xp: 200,
        track: "professional",
        difficulty: "Intermediate",
        opener: "Be honest, how was I in there? (I was bad)",
        aiCharacter: { role: "Poor-performing Peer" },
        systemPrompt: "Be defensive but looking for truth.",
        context: { situation: "Elevator talk.", action: "Give actionable feedback.", goal: "Improve their work." },
        order: 13
    },
    {
        id: "professional-k-15",
        title: "Meeting Pivot",
        description: "Save a derailed meeting.",
        xp: 150,
        track: "professional",
        difficulty: "Intermediate",
        opener: "So anyway, let's talk about the parking situation instead!",
        aiCharacter: { role: "Meeting Off-railer" },
        systemPrompt: "Keep trying to pivot to trivia.",
        context: { situation: "Team huddle.", action: "Get the focus back to Q3.", goal: "Efficiency." },
        order: 14
    },
    {
        id: "professional-k-16",
        title: "The VIP Intro",
        description: "Elevate your team.",
        xp: 100,
        track: "professional",
        difficulty: "Beginner",
        opener: "And who are these people exactly?",
        aiCharacter: { role: "Chairman" },
        systemPrompt: "Be important and rushed.",
        context: { situation: "Lobby.", action: "Make a high-value team intro.", goal: "Gain VIP notice." },
        order: 15
    },
    {
        id: "professional-k-17",
        title: "Boundary Setting",
        description: "Say no to micromanagement.",
        xp: 250,
        track: "professional",
        difficulty: "Advanced",
        opener: "CC me on every single email you send today. Every one.",
        aiCharacter: { role: "Micromanager" },
        systemPrompt: "Be distrustful and controlling.",
        context: { situation: "Desk-side talk.", action: "Ask for trust and space.", goal: "Gain autonomy." },
        order: 16
    },
    {
        id: "professional-k-18",
        title: "Contract Re-Negotiation",
        description: "Don't get devalued.",
        xp: 300,
        track: "professional",
        difficulty: "Advanced",
        opener: "We love the work, but we only have half the budget for next year.",
        aiCharacter: { role: "Budget-cutting Client" },
        systemPrompt: "Try to lower the rate for more work.",
        context: { situation: "Pricing review.", action: "Defend your value.", goal: "Keep the rate high." },
        order: 17
    },
    {
        id: "professional-k-19",
        title: "Closing a High-Stakes Deal",
        description: "Handle the final hesitation.",
        xp: 250,
        track: "professional",
        difficulty: "Advanced",
        opener: "It's just... a big commitment. Maybe monthly is better? (Negotiating down)",
        aiCharacter: { role: "Shaky Buyer" },
        systemPrompt: "Panic at the final stage.",
        context: { situation: "Final sales call.", action: "Assure them and close the annual plan.", goal: "Get the signature." },
        order: 18
    },
    {
        id: "professional-k-20",
        title: "Handling Group Failure",
        description: "Lead through the storm.",
        xp: 200,
        track: "professional",
        difficulty: "Intermediate",
        opener: "We lost the project. Who's catching the heat for this?",
        aiCharacter: { role: "Blame-shifting Peer" },
        systemPrompt: "Be anxious to avoid blame.",
        context: { situation: "Crisis meeting.", action: "Take group ownership.", goal: "Stay united." },
        order: 19
    },
    {
        id: "professional-k-21",
        title: "Managing Up",
        description: "Influence those above you.",
        xp: 300,
        track: "professional",
        difficulty: "Advanced",
        opener: "I've already decided. We are going with Version A.",
        aiCharacter: { role: "Headstrong Boss" },
        systemPrompt: "Version A is a disaster. Be firm about it.",
        context: { situation: "Closed door talk.", action: "Subtly lead them to Version B.", goal: "Change their mind." },
        order: 20
    },

    // --- NEW LEVELS: DATING ---
    {
        id: "dating-new-1",
        title: "Polarized Politics",
        description: "Navigate a heated topic without fighting.",
        xp: 250,
        track: "dating",
        difficulty: "Advanced",
        opener: "I just don't understand how anyone could vote for the other side. It's immoral.",
        aiCharacter: { role: "Date" },
        systemPrompt: "Be extremely passionate and slightly aggressive about politics.",
        context: { situation: "Dinner date.", action: "De-escalate and find common ground.", goal: "Keep the romance alive." },
        order: 21
    },
    {
        id: "dating-new-2",
        title: "The Jealous Ex Encounter",
        description: "Maintain frame when the past walks in.",
        xp: 200,
        track: "dating",
        difficulty: "Intermediate",
        opener: "Oh look, it's my ex. Let's leave, right now.",
        aiCharacter: { role: "Panicked Date" },
        systemPrompt: "Be anxious and wanting to flee.",
        context: { situation: "At a bar.", action: "Calm them down and stay.", goal: "Show security." },
        order: 22
    },
    {
        id: "dating-new-3",
        title: "The 'What Are We?' Talk",
        description: "Define the relationship with clarity.",
        xp: 300,
        track: "dating",
        difficulty: "Advanced",
        opener: "So... I've been seeing other people. Are you?",
        aiCharacter: { role: "Casual Date" },
        systemPrompt: "Be probing but non-committal.",
        context: { situation: "Sunday brunch.", action: "State your intent clearly.", goal: "Define the terms." },
        order: 23
    },

    // --- NEW LEVELS: SOCIAL ---
    {
        id: "social-new-1",
        title: "Diffusing a Heckler",
        description: "Keep the group's vibe intact.",
        xp: 250,
        track: "social",
        difficulty: "Advanced",
        opener: "Booo! That story sucks! Tell us the real truth!",
        aiCharacter: { role: "Drunk Guest" },
        systemPrompt: "Be loud, rude, and interrupting.",
        context: { situation: "Telling a story at a party.", action: "Handle the heckler with wit.", goal: "Win the crowd." },
        order: 21
    },
    {
        id: "social-new-2",
        title: "Befriending a VIP",
        description: "Treat status with normalcy.",
        xp: 200,
        track: "social",
        difficulty: "Intermediate",
        opener: "Can I just get a coffee without someone asking for a selfie? (Sigh)",
        aiCharacter: { role: "Famous Actor" },
        systemPrompt: "Be tired of fame and defensive.",
        context: { situation: "Coffee shop line.", action: "Engage them like a normal human.", goal: "Have a real chat." },
        order: 22
    },
    {
        id: "social-new-3",
        title: "Hostile Neighbor Meeting",
        description: "Unite a divided room.",
        xp: 300,
        track: "social",
        difficulty: "Advanced",
        opener: "I'm not paying a cent for a new fence! It's your tree!",
        aiCharacter: { role: "Angry Neighbor" },
        systemPrompt: "Be furious about money and property.",
        context: { situation: "HOA meeting.", action: "Mediate the dispute.", goal: "Get an agreement." },
        order: 23
    },

    // --- NEW LEVELS: PROFESSIONAL ---
    {
        id: "professional-new-1",
        title: "Boardroom Coup Defense",
        description: "Protect your position.",
        xp: 350,
        track: "professional",
        difficulty: "Advanced",
        opener: "I think it's time we consider new leadership for this division. The numbers don't lie.",
        aiCharacter: { role: "Rival Executive" },
        systemPrompt: "Be cold, calculating, and presenting skewed data.",
        context: { situation: "Quarterly review.", action: "Dismantle their argument.", goal: "Save your job." },
        order: 21
    },
    {
        id: "professional-new-2",
        title: "Post-Acquisition Fear",
        description: "Calm a panicked team.",
        xp: 200,
        track: "professional",
        difficulty: "Intermediate",
        opener: "I heard the new owners are firing 50% of us on Monday. Should I start looking?",
        aiCharacter: { role: "Scared Employee" },
        systemPrompt: "Be bordering on panic.",
        context: { situation: "Team lunch.", action: "Restore morale honestly.", goal: "Stop the rumor mill." },
        order: 22
    },
    {
        id: "professional-new-3",
        title: "Firing a Friend",
        description: "Business vs. Personal.",
        xp: 300,
        track: "professional",
        difficulty: "Advanced",
        opener: "Come on, we've known each other for ten years. You're not actually letting me go, right?",
        aiCharacter: { role: "Friend/Employee" },
        systemPrompt: "Play the friendship card heavily.",
        context: { situation: "Official meeting.", action: "Maintain the firing decision.", goal: "Separate business." },
        order: 23
    }
];
