
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service – Verlo AI",
    description:
        "Read the Verlo AI Terms of Service. By accessing or using the App, you agree to be bound by these Terms.",
};

export default function TermsOfServicePage() {
    return (
        <div className="page-container" id="terms-of-service-page">
            <div className="page-header">
                <div className="page-badge">⚖️ Legal</div>
                <h1 className="page-title">Terms of Service</h1>
                <p className="page-subtitle">
                    Welcome to Verlo AI! These Terms define the relationship between you and Verlo AI.
                </p>
                <p className="page-last-updated">Last Updated: February 16, 2026</p>
            </div>

            {/* Table of Contents */}
            <div className="toc" id="terms-toc">
                <h3>Table of Contents</h3>
                <ol className="toc-list">
                    <li><a href="#section-1"><span className="toc-number">01</span> Description of Service</a></li>
                    <li><a href="#section-2"><span className="toc-number">02</span> Artificial Intelligence Disclaimer</a></li>
                    <li><a href="#section-3"><span className="toc-number">03</span> User Accounts</a></li>
                    <li><a href="#section-4"><span className="toc-number">04</span> Subscriptions and Billing</a></li>
                    <li><a href="#section-5"><span className="toc-number">05</span> User Conduct</a></li>
                    <li><a href="#section-6"><span className="toc-number">06</span> Intellectual Property</a></li>
                    <li><a href="#section-7"><span className="toc-number">07</span> Limitation of Liability</a></li>
                    <li><a href="#section-8"><span className="toc-number">08</span> Disclaimer</a></li>
                    <li><a href="#section-9"><span className="toc-number">09</span> Governing Law</a></li>
                    <li><a href="#section-10"><span className="toc-number">10</span> Changes</a></li>
                    <li><a href="#section-11"><span className="toc-number">11</span> Contact Us</a></li>
                </ol>
            </div>

            <div className="policy-content">
                <section className="policy-section" id="section-1">
                    <div className="policy-section-number">1</div>
                    <h2>Description of Service</h2>
                    <p>
                        Verlo AI is an AI-powered conversation coaching application designed to help users improve their social skills, confidence, and charisma through simulated conversations with AI characters.
                    </p>
                    <p>
                        These Terms of Service ("Terms") enable you to use Verlo AI, a mobile application application ("App") operated by Verlo AI ("us", "we", or "our").
                    </p>
                    <p>
                        By accessing or using the App, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the App.
                    </p>
                </section>

                <section className="policy-section" id="section-2">
                    <div className="policy-section-number">2</div>
                    <h2>Artificial Intelligence Disclaimer</h2>
                    <h3>2.1 AI-Generated Content</h3>
                    <p>
                        You acknowledge that the conversations and feedback provided within the App are generated by artificial intelligence. While we strive for realism and helpfulness, AI responses may occasionally be inaccurate, inappropriate, or nonsensical. You agree that Verlo AI is not responsible for any advice or content generated by the AI characters.
                    </p>
                    <h3>2.2 No Professional Advice</h3>
                    <p>
                        The App provides social skills practice and coaching for entertainment and self-improvement purposes only. It is not a substitute for professional psychological, psychiatric, or medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical or mental health condition.
                    </p>
                </section>

                <section className="policy-section" id="section-3">
                    <div className="policy-section-number">3</div>
                    <h2>User Accounts</h2>
                    <h3>3.1 Registration</h3>
                    <p>
                        To access certain features of the App, you may be required to register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
                    </p>
                    <h3>3.2 Security</h3>
                    <p>
                        You are responsible for safeguarding the password that you use to access the App and for any activities or actions under your password. You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
                    </p>
                </section>

                <section className="policy-section" id="section-4">
                    <div className="policy-section-number">4</div>
                    <h2>Subscriptions and Billing</h2>
                    <h3>4.1 Subscriptions</h3>
                    <p>
                        Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in advance on a recurring and periodic basis ("Billing Cycle"). Billing cycles are set either on a monthly or annual basis, depending on the type of subscription plan you select when purchasing a Subscription.
                    </p>
                    <h3>4.2 Payment via Apple App Store</h3>
                    <p>
                        All purchases and subscriptions are processed through the Apple App Store ("Apple"). You acknowledge and agree that you are entering into a transaction with Apple, not Verlo AI, and that your use of the App is subject to Apple's then-current Terms and Conditions.
                    </p>
                    <h3>4.3 Automatic Renewal</h3>
                    <p>
                        Your Subscription will automatically renew at the end of each Billing Cycle unless you cancel it or Verlo AI cancels it. You may cancel your Subscription renewal either through your online account management page or by contacting Apple customer support.
                    </p>
                    <h3>4.4 Refunds</h3>
                    <p>
                        All refund requests must be directed to Apple support, as they handle the billing for the App. Verlo AI does not process refunds directly.
                    </p>
                </section>

                <section className="policy-section" id="section-5">
                    <div className="policy-section-number">5</div>
                    <h2>User Conduct</h2>
                    <p>You agree not to use the App to:</p>
                    <ul>
                        <li>Engage in any illegal, abusive, harassing, or harmful behavior.</li>
                        <li>Generate or attempt to generate content that is sexually explicit, hateful, violent, or otherwise violates our community standards.</li>
                        <li>Reverse engineer, decompile, or attempt to extract the source code of the App.</li>
                        <li>Use the App for any purpose other than personal self-improvement and entertainment.</li>
                    </ul>
                </section>

                <section className="policy-section" id="section-6">
                    <div className="policy-section-number">6</div>
                    <h2>Intellectual Property</h2>
                    <p>
                        The App and its original content (excluding AI-generated conversations), features, and functionality are and will remain the exclusive property of Verlo AI and its licensors. The App is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Verlo AI.
                    </p>
                </section>

                <section className="policy-section" id="section-7">
                    <div className="policy-section-number">7</div>
                    <h2>Limitation of Liability</h2>
                    <p>
                        In no event shall Verlo AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the App; (ii) any conduct or content of any third party on the App; (iii) any content obtained from the App; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.
                    </p>
                </section>

                <section className="policy-section" id="section-8">
                    <div className="policy-section-number">8</div>
                    <h2>Disclaimer</h2>
                    <p>
                        Your use of the App is at your sole risk. The App is provided on an "AS IS" and "AS AVAILABLE" basis. The App is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.
                    </p>
                </section>

                <section className="policy-section" id="section-9">
                    <div className="policy-section-number">9</div>
                    <h2>Governing Law</h2>
                    <p>
                        These Terms shall be governed and construed in accordance with the laws of the United States, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
                    </p>
                </section>

                <section className="policy-section" id="section-10">
                    <div className="policy-section-number">10</div>
                    <h2>Changes</h2>
                    <p>
                        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
                    </p>
                </section>

                <section className="policy-section" id="section-11">
                    <div className="policy-section-number">11</div>
                    <h2>Contact Us</h2>
                    <p>If you have any questions about these Terms, please contact us:</p>
                    <ul>
                        <li>
                            By email: <a href="mailto:support@verloai.com" style={{ color: "var(--text-accent)" }}>support@verloai.com</a>
                        </li>
                        <li>
                            By visiting this page on our website: <a href="https://verloai.vercel.app/contact" style={{ color: "var(--text-accent)" }}>https://verloai.vercel.app/contact</a>
                        </li>
                    </ul>
                </section>
            </div>
        </div>
    );
}
